from tkinter import *
from tkinter import ttk
from sqlite_book import sql_book
from sqlite_user import sql_user
class admin_system(object):
    def __init__(self,master,name):
        self.root = master
        self.root.geometry("800x600")
        canvas = Canvas(self.root)
        canvas.create_line(0, 27, 2000, 27, tags="line")
        canvas.pack(side=TOP, fill=X, pady=10)
        Button(canvas, text = "图书操作",relief=GROOVE,command=self.create_windows1).pack(side=LEFT, padx =10)
        Button(canvas, text = "用户操作",relief=GROOVE,command=self.create_windows2).pack(side=LEFT, padx =5)
        Label(canvas,text=f"{name}，欢迎进入图书管理系统").pack(side=LEFT, expand= YES)
        self.Frm_Book = Frame(self.root)
        self.Frm_Book.pack(expand=YES, fill=BOTH)
        frm_2 = Frame(self.Frm_Book)
        frm_2.pack(side=LEFT,fill = Y,padx= 10)
        Entry(frm_2).pack(fill=X,pady=10)
        type = ["经典著作","社会科学","军事科学","计算机技术","生活休闲","期刊","文学教育","音乐","摄影影视"]
        self.tree = ttk.Treeview(frm_2)
        for type_ in type:
            self.tree.insert("", 0, type_, text=type_)
        self.tree.pack(side = LEFT, expand=YES,fill = Y)

        frm_3 = Frame(self.Frm_Book)
        frm_3.pack(expand=YES)
        frm_31 = Frame(frm_3)
        frm_31.pack(side=LEFT,expand=YES,fill=Y)
        Label(frm_31, text="书   名：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=10)
        Label(frm_31, text="作   者：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=10)
        Label(frm_31, text="出 版 社：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=10)
        Label(frm_31, text="ISBN：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=5)
        Label(frm_31, text="库   存：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=10)
        Label(frm_31, text="已   借：",width=8,font=('Arial',20),justify=LEFT).pack(side=TOP, padx=10,pady=10)
        frm_32 = Frame(frm_3)
        frm_32.pack(side=LEFT,expand=YES,fill=Y)
        var1 = StringVar(value="大数据挖掘与计算")
        Entry(frm_32,textvariable = var1,state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        var2 = StringVar(value="李白")
        Entry(frm_32, textvariable=var2, state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        var3 = StringVar(value="重庆第二师范学院")
        Entry(frm_32, textvariable=var3, state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        var4 = StringVar(value="123456789")
        Entry(frm_32, textvariable=var4, state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        var5 = StringVar(value="99")
        Entry(frm_32, textvariable=var5, state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        var6 = StringVar(value="0")
        Entry(frm_32, textvariable=var6, state=DISABLED,font=('Arial',20)).pack(side=TOP, padx=20,pady=10)
        frm_33 = Frame(self.Frm_Book)
        frm_33.pack(expand=YES)
        Button(frm_33, text="添加图书", relief=GROOVE,font=('Arial',20)).pack(side=LEFT,padx=20)
        Button(frm_33, text="修改图书", relief=GROOVE,font=('Arial',20)).pack(side=LEFT,padx=20)
        Button(frm_33, text="删除图书", relief=GROOVE,font=('Arial',20)).pack(side=LEFT,padx=20)

        self.Frm_User = Frame(self.root)
        frm_4 = Frame(self.Frm_User)
        frm_4.pack(side=LEFT,fill=Y, padx=10)
        Entry(frm_4).pack(fill=X,pady=10)
        Listbox(frm_4).pack(side=LEFT,fill=Y,expand=YES)
        frm_5 = Frame(self.Frm_User)
        frm_5.pack(expand=YES)
        frm_51 = Frame(frm_5)
        frm_51.pack(side=LEFT, expand=YES, fill=Y)
        Label(frm_51, text="姓   名：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=10)
        Label(frm_51, text="学   校：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=10)
        Label(frm_51, text="账   号：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=10)
        Label(frm_51, text="密   码：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=10)
        Label(frm_51, text="额   度：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=5)
        Label(frm_51, text="已   借：", width=8, font=('Arial', 20), justify=LEFT).pack(side=TOP, padx=10, pady=10)
        frm_52 = Frame(frm_5)
        frm_52.pack(side=LEFT, expand=YES, fill=Y)
        var1 = StringVar(value="张三")
        Entry(frm_52, textvariable=var1, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=10)
        var2 = StringVar(value="重庆第二师范学院")
        Entry(frm_52, textvariable=var2, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=10)
        var3 = StringVar(value="123456")
        Entry(frm_52, textvariable=var3, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=13)
        var4 = StringVar(value="123456789")
        Entry(frm_52, textvariable=var4, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=10)
        var5 = StringVar(value="100")
        Entry(frm_52, textvariable=var5, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=10)
        var6 = StringVar(value="0")
        Entry(frm_52, textvariable=var6, state=DISABLED, font=('Arial', 20)).pack(side=TOP, padx=20, pady=10)
        frm_53= Frame(self.Frm_User)
        frm_53.pack(expand=YES)
        Button(frm_53, text="添加用户", relief=GROOVE, font=('Arial', 20)).pack(side=LEFT, padx=10)
        Button(frm_53, text="更新用户", relief=GROOVE, font=('Arial', 20)).pack(side=LEFT, padx=10)
        Button(frm_53, text="删除用户", relief=GROOVE, font=('Arial', 20)).pack(side=LEFT, padx=10)
        Button(frm_53, text="借阅记录", relief=GROOVE, font=('Arial', 20)).pack(side=LEFT, padx=10)
    def create_windows1(self):
        self.Frm_Book.pack_forget()
        self.Frm_User.pack_forget()
        self.Frm_Book.pack(expand=YES, fill=BOTH)
    def create_windows2(self):
        self.Frm_Book.pack_forget()
        self.Frm_User.pack_forget()
        self.Frm_User.pack(expand=YES, fill=BOTH)
if __name__ == '__main__':
    root = Tk()
    start = admin_system(root)
    root.mainloop()